#!/usr/bin/env bash
# transfer file from our machine to SSH server

if [ $# -lt 3 ]
then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
elif [ $# -eq 3 ]
then
    scp "$1" "$3@$2:~/" -o StrictHostKeyChecking=no
else
    scp -i "$4" "$1" "$3@$2:~/" -o StrictHostKeyChecking=no
fi