#!/usr/bin/env bash
# Update Nginx config to create a permanent redirection
sudo apt-get update
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sed "/server_name _;/a rewrite ^/redirect_me/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4$1 permanent;" /etc/nginx/sites-available/default
service nginx restart