#!/usr/bin/env bash
# Nginx configuration | custom 404 page
echo "Ceci n'est pas une page" | sudo tee -a /usr/share/nginx/html/404.html
sed -i "/listen [::]:80 default_server;/a error_page 404 /404.html;location = /404.html { root /usr/share/nginx/html; internal; }" /etc/nginx/sites-available/default
sudo service nginx restart
