#!/usr/bin/env bash
# Read /etc/passwd and tell an story
file="/etc/passwd"
while IFS=: read -r username password userid groupid comment homedir shell
do
    echo "The user $username is part of the $groupid gang lives in $homedir and rides $shell. $userid's place is protected by the passcode $password more info about the user here: $comment"
done < "$file"