#!/usr/bin/env bash
# displays Holberton School 10 times, but for the 9th iteration, displays 
# Holberton School and then Hi on a new line.
i=1
while [ $i -le 10 ]
do
    if [ $i == 9 ]; then
        echo "Holberton School"
        echo "Hi"
        i=$(( i + 1 ))
    else
        echo "Holberton School"
        i=$(( i + 1 ))
    fi
done