#!/usr/bin/env bash
# Using while loop and case statement
i=1
while [ $i -le 20 ]
do
    case $i in
        4 )
            echo "bad luck from China" ;;
        8 )
            echo "bad luck from Japan" ;;
        17)
            echo "bad luck from Italy" ;;
        * )
            echo "$i" ;;
    esac
    i=$(( i + 1 ))
done