#!/usr/bin/env bash
# Content of the current directory in a list format, where
# only the part of the name after the first dash is displayed
filenames=$(ls)
for filename in $filenames; do
   echo "$filename" | cut -d "-" -f2
done