#!/usr/bin/env bash
# Check if the file exists
filename="holbertonschool"
if [ -e "$filename" ]; then
    echo "holbertonschool file exists"
    if [ -s "$filename" ]; then
        echo "holbertonschool file is not empty"
        if [ -f "$filename" ]; then
            echo "holbertonschool is a regular file"
        fi
    else
        echo "holbertonschool file is empty"
    fi
else
    echo "holbertonschool file does not exist"
fi